apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: dollypizzle-multi-k8s-tls
spec:
  secretName: dollypizzle-multi-k8s
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: dollypizzle-multi-k8s.tk
  dnsNames:
    - dollypizzle-multi-k8s.tk
    - www.dollypizzle-multi-k8s.tk
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - dollypizzle-multi-k8s.tk
          - www.dollypizzle-multi-k8s.tk
